---
title: "Creative Assignment 7"
author: "Zoe Iacovino"
date: "11/1/2020"
output: html_document
---

```{r Loading Libraries, results='hide', message=FALSE}
library(tidycensus)
library(tidyverse)
options(tigris_use_cache = TRUE)
#to import tigerlines directly into my census data (https://walker-data.com/tidycensus/articles/spatial-data.html)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(raster)
library(gstat)
library(spatial)

```

```{r Loading Data, results = 'hide', message=FALSE}
#Evictions Data: Evictions Filed in and around Boston. Average for 2012, 2013, 2015, 2016
evictions <- read.csv("boston_evictions.csv")%>%
  group_by(GEOID) %>% 
  summarize(filings_2020 = sum(filings_2020),
            filings_avg = sum(filings_avg, na.rm = T))
  

data_source <- "Peter Hepburn, Renee Louis, and Matthew Desmond. Eviction Tracking System: Version 1.0. Princeton: Princeton University, 2020. www.evictionlab.org."

#Census Tract Lines and rental data
v18 <- load_variables(2018, "acs5", cache = FALSE)

# B19054_001 Rental Income of the Last 12 Months
# B25008_003 Total Population of Renters

acs18_data <- get_acs(state = "MA", county = c("Suffolk","Middlesex"), geography = "tract",
                  variables = c("B19054_001", "B25008_003"), geometry = TRUE)%>%
              mutate(variable = case_when(variable == "B19054_001" ~ "rIncome",
                                          variable == "B25008_003" ~ "rPop"))%>%
              

cen_sub <- acs18_data[evictions,]


bos_evict <- inner_join(evictions, acs18_data, by = "GEOID")
#are my zeroes zeroes or no datas? 

```



