---
title: "Creative Assignment 4"
author: "Zoe Iacovino"
date: "10/4/2020"
output: html_document
---

```{r Libraries, results = 'hide', message=FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
library(units)
```


```{r Loading Data}
polling_loc<- st_read("https://data.cambridgema.gov/api/geospatial/krvc-8hz2?method=export&format=KML")
```

```{r Loading OSM}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

cambridge_street_features <- opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

cambridge_streets <- cambridge_street_features$osm_lines %>%
  st_transform(crs = MA_state_plane)
```

```{r Plotting Streep Map}
ggplot(cambridge_streets) +
  geom_sf() +
  theme_map()


```
```{r}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")
otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```
```{r Setting up OTP}
otp_setup(otp = path_otp, dir = path_data, memory =1024)
# Connect to opentripplanner
otpcon <- otp_connect()
```


## Creating Isochrones
```{r}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = polling_loc, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "walk")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = polling_loc, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_5min_drive, iso_5min_walk)

otp_stop()

```


## 5 Minute Walk and Drivesheds for Cambridge Polling Locations
```{r}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "hotstyle", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = polling_loc) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```


## Walking and Driving Walkshed Comparison
```{r Comparing Isochron areas}
iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area, values_fn= mean) %>%
  filter(!is.na(drive), !is.na(walk))

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a polling location\n(square km)",
            breaks = breaks <- seq(10000, 130000, by = 20000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a polling location\n(square km)",
            breaks = breaks <- seq(0, 700000, by = 100000),
            labels = breaks / 1000000) +
  theme_solarized_2()
```

## Areas and Overlapping Isochrones
```{r overlapping isochrone}

iso_overlap <- iso_all_modes%>%
  mutate(num_overlaps = (lengths(st_overlaps(iso_all_modes))))%>%
  mutate(has_overlaps = num_overlaps > 0)%>%
  mutate(area = (st_area(iso_all_modes)))

ggplot(iso_overlap, 
       aes(x = as.numeric(area),
           y = num_overlaps,
           color = mode)) +
  geom_point(alpha = 0.5, size = 1.5) +
  scale_colour_fivethirtyeight()+
  #stat_smooth(color = "#dfc7f2", linetype = 2, size = 1.5) +
  scale_y_continuous(name = "Number of Overlaps with other travel sheds",
                     labels = c("0", "1", "2", "3", "4", "5", "6"),
                     breaks = seq(0, 6, by = 1)) +
  scale_x_continuous(name = "Area of Isochrone in square meters",
                     labels = c("0 or 700,000", "100,000", "200,000", "300,000", "400,000", "500,000", "600,000", "700,000"),
                     breaks = seq(0, 700000, by= 100000))+
  coord_polar(theta = "x")+
  theme_solarized()


```

